import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { LadderItem } from "@/components/Ladder/LadderItem/LadderItem";
import { Ladder } from "@/components/Ladder/Ladder";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Ladder
        players={[
          {
            email: "marc@poolladder.com",
            position: 1,
            canChallenge: false,
          },
          {
            email: "eb@poolladder.com ",
            position: 2,
            canChallenge: true,
          },
          {
            email: "sj@poolladder..com",
            position: 3,
            canChallenge: true,
          },
          {
            email: "mw@poolladder.com ",
            position: 4,
            canChallenge: false,
          },
          {
            email: "pc@poolladder.com",
            position: 5,
            canChallenge: true,
          },
        ]}
      />
    </>
  );
}
